### ISSUE TITLE
Setting to disable autoscrobble anime

### ISSUE THREAD

**Issue by reitenth** [crobibero/jellyfin-plugin-simkl#6]
I was wondering if you could add a setting to autoscrobble anime like there is with Movies and TV shows as I want them to scrobble, but not the anime I watch. Thanks.

**Comment by crobibero** [comment]
Anime and (TV/Movies) are the same type, so the only thing I could do is add a library filter

**Comment by reitenth** [comment]
Something like Trakt then? The Trakt plugin has a setting to choose which folders in your Jellyfin library scrobble so I have tv shows and movies checked but not my anime library. Sorry if this is picky, I use Anilist for anime and don't like seeing anime on Simkl but prefer it greatly over Trakt. Thanks for the time.
